name: DevContainer CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-devcontainer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Start services (Build + Run)
    - name: Build and start devcontainer
      run: |
        docker compose -f .devcontainer/docker-compose.yml up -d --build

    # Optional: Check running status
    - name: Check container health
      run: docker ps --filter "status=running"

    - name: Shut down
      if: always()
      run: docker compose -f .devcontainer/docker-compose.yml down
